[package]
name = "rust_shellcode_example"
version = "0.1.0"
edition = "2021"

[dependencies]

winapi = { version = "0.3.9", features = [
     "memoryapi",
     "minwinbase",
     "processthreadsapi",
     "synchapi",
     "winnt",
] }
